-- eccoai's own template library. Original skeletons across the common
-- LinkedIn post families. Replaces earlier global seeds.
DELETE FROM post_structures WHERE user_id IS NULL;

INSERT INTO post_structures (name, hook_type, description, skeleton, approved, user_id) VALUES
  ('Best advice I ever got', 'Best advice',
   'Open with a line of advice, the moment it landed, and what it means to you now.',
   E'The best advice I ever got: {the advice}.\n\nAt the time, I {initial reaction}.\n\nYears later, here is what it really meant: {deeper meaning}.\n\n{how you use it now}', true, NULL),
  ('One thing I would tell you', 'Best advice',
   'Speak directly to a specific reader and hand them one hard-won truth.',
   E'If you are {audience or situation}, hear this:\n\n{core message}.\n\nNobody tells you {the hard truth}.\n\nSo here is the move: {practical takeaway}.', true, NULL),
  ('What I wish I knew', 'Best advice',
   'A short list of lessons framed as what you wish you had known earlier.',
   E'{number} things I wish I knew before {milestone}:\n\n1. {lesson}\n2. {lesson}\n3. {lesson}\n\nThe one that changed everything: {the key lesson}.', true, NULL),
  ('Exactly how I do it', 'Method',
   'A tactical, step-by-step walkthrough of a real process the reader can copy.',
   E'Here is exactly how I {outcome}, step by step:\n\n1. {step}\n2. {step}\n3. {step}\n4. {step}\n\nThe step everyone skips: {the overlooked step}.', true, NULL),
  ('The framework', 'Method',
   'Name a simple framework, break down its parts, then ground it in an example.',
   E'I use a simple framework for {problem}. I call it {name}.\n\n{part 1} = {meaning}\n{part 2} = {meaning}\n{part 3} = {meaning}\n\nTry it on {concrete example}.', true, NULL),
  ('Zero to one', 'Method',
   'Map the journey from a starting point to an outcome in clear phases.',
   E'How to go from {starting point} to {end point}:\n\nPhase 1: {what to do}\nPhase 2: {what to do}\nPhase 3: {what to do}\n\nStart today with {first action}.', true, NULL),
  ('The tip that took me years', 'Tip',
   'One sharp, specific tip plus the reason it works.',
   E'A {topic} tip that took me {time} to learn:\n\n{the tip}.\n\nWhy it works: {reason}.\n\nSteal it.', true, NULL),
  ('Do this, not that', 'Tip',
   'A crisp swap: the common approach versus the better one.',
   E'Stop {common approach}.\n\nStart {better approach}.\n\nThe difference: {what changes}.', true, NULL),
  ('The two-minute fix', 'Tip',
   'A tiny action that solves a common struggle, with the why.',
   E'If you {common struggle}, do this for two minutes: {the action}.\n\nIt fixes {the problem} because {reason}.', true, NULL),
  ('My actual toolkit', 'Tools',
   'A save-worthy list of the tools you genuinely use for a job.',
   E'The {number} tools I actually use for {job}:\n\n1. {tool} - {what for}\n2. {tool} - {what for}\n3. {tool} - {what for}\n\nSave this. What would you add?', true, NULL),
  ('The one resource', 'Tools',
   'If the reader uses only one thing, make it this, and show how.',
   E'If you only use one thing for {goal}, make it this: {the resource}.\n\nHere is how I use it: {how}.', true, NULL),
  ('The mistake that cost me', 'Mistakes',
   'Name a costly mistake, what you did wrong, and the right move.',
   E'The {topic} mistake that cost me {what it cost}:\n\nI {what you did wrong}.\n\nWhat I should have done: {the right move}.\n\nDo not repeat it.', true, NULL),
  ('Red flags I ignored', 'Mistakes',
   'A short list of warning signs you missed, and what to do about them.',
   E'{number} red flags I ignored in {situation}:\n\n- {red flag}\n- {red flag}\n- {red flag}\n\nIf you see these: {what to do}.', true, NULL),
  ('Stop doing this', 'Mistakes',
   'Call out a common mistake, why it backfires, and the alternative.',
   E'Stop {common mistake}. I see it constantly.\n\nHere is why it backfires: {consequence}.\n\nDo this instead: {alternative}.', true, NULL),
  ('The number', 'Milestone',
   'Lead with a milestone number, its meaning, gratitude, and what is next.',
   E'{specific number}.\n\nThat is {what it represents}.\n\nWhat it really means: {deeper meaning}.\n\nThank you to {people who helped}.\n\nNext: {forward goal}.', true, NULL),
  ('What this year taught me', 'Milestone',
   'Reflect on a period of time through a few honest lessons.',
   E'{time period} ago, I {started something}.\n\nHere is what it taught me:\n\n- {lesson}\n- {lesson}\n- {lesson}\n\nHere is to {what is next}.', true, NULL),
  ('The turning point', 'My story',
   'A vulnerable before and after: a low moment, the choice, the change.',
   E'{time ago}, I {low moment}.\n\nEveryone said {common advice}.\n\nInstead, I {the choice}.\n\nHere is what changed:\n\n- {shift}\n- {shift}\n\n{one-line takeaway}', true, NULL),
  ('Why I really started', 'My story',
   'The honest reason behind what you do, and what it means for the work.',
   E'People ask why I {what you do}.\n\nThe real reason: {the story or moment}.\n\n{what it means for the work now}.', true, NULL),
  ('I almost quit', 'My story',
   'A raw moment of nearly giving up, and what kept you going.',
   E'I almost quit {thing} {time ago}.\n\n{what was happening}.\n\nWhat kept me going: {the reason}.\n\nIf you are there right now: {message to the reader}.', true, NULL),
  ('Unpopular opinion', 'Contrarian',
   'State a contrarian take, name the consensus, then defend your view.',
   E'Unpopular opinion: {the take}.\n\nEveryone says {conventional wisdom}. I disagree.\n\nHere is why: {reasoning}.\n\n{what to do with this}.', true, NULL),
  ('The biggest lie', 'Contrarian',
   'Name a widely repeated falsehood in your space, then the truth.',
   E'The biggest lie in {industry or topic}: {the lie}.\n\nThe truth: {reality}.\n\nWhat changes when you accept it: {implication}.', true, NULL),
  ('The stat that stops you', 'Data',
   'Lead with a surprising number, make it human, and raise the real question.',
   E'{surprising statistic}.\n\nLet that sink in.\n\nBehind that number: {what it means for real people}.\n\n{the question this should force us to ask}', true, NULL),
  ('If I started over', 'Lessons',
   'What you would change, and the one thing you would keep exactly.',
   E'If I started {thing} over today, here is what I would do differently:\n\n- {change}\n- {change}\n- {change}\n\nWhat I would keep exactly the same: {the one thing}.', true, NULL);
INSERT INTO post_structures (name, hook_type, description, skeleton, approved, user_id) VALUES
  ('The advice nobody follows', 'Best advice', 'Advice that is obvious but rarely acted on, and why.',
   E'The best {topic} advice is also the most ignored:\n\n{the advice}.\n\nEveryone nods. Almost no one does it.\n\nHere is how to actually start: {first step}.', true, NULL),
  ('The checklist', 'Method', 'A repeatable checklist the reader can run every time.',
   E'Before I {action}, I run this checklist:\n\n- {check}\n- {check}\n- {check}\n- {check}\n\nMiss one, and {consequence}. Save it.', true, NULL),
  ('My weekly routine', 'Method', 'A simple routine that produces results over time.',
   E'The routine that changed my {area}:\n\nMonday: {habit}\nMidweek: {habit}\nFriday: {habit}\n\nBoring on purpose. That is why it works.', true, NULL),
  ('Underrated tip', 'Tip', 'A small, overlooked tactic with outsized impact.',
   E'Most underrated {topic} tip:\n\n{the tip}.\n\nIt takes {effort} and changes {result}. Try it this week.', true, NULL),
  ('The free alternative', 'Tools', 'A no-cost way to get what expensive tools promise.',
   E'You do not need {expensive thing} to {goal}.\n\nDo this instead, for free: {alternative}.\n\nHere is exactly how: {how}.', true, NULL),
  ('What I got wrong', 'Mistakes', 'An honest admission of a belief or move that was wrong.',
   E'I was wrong about {topic}.\n\nI believed {old belief}.\n\nWhat changed my mind: {the turning point}.\n\nWhat I believe now: {new belief}.', true, NULL),
  ('The small win', 'Milestone', 'Celebrate a modest but meaningful step and why it matters.',
   E'Small win: {the win}.\n\nNot flashy. But it means {why it matters}.\n\nThe next small step: {next}.', true, NULL),
  ('The rejection', 'My story', 'A rejection that redirected you, and what it taught you.',
   E'{who or what} said no.\n\nAt the time it felt like {feeling}.\n\nLooking back, that no gave me {the gift}.\n\nIf you just got a no: {message}.', true, NULL),
  ('How it started vs now', 'My story', 'A then-and-now contrast that shows growth.',
   E'How it started: {early reality}.\n\nHow it is going: {current reality}.\n\nWhat bridged the two: {the work}.', true, NULL),
  ('Hot take', 'Contrarian', 'A bold, defensible claim stated plainly.',
   E'Hot take: {the claim}.\n\nI know that is not popular.\n\nBut {reasoning}.\n\nChange my mind.', true, NULL),
  ('Nobody wants to say it', 'Contrarian', 'Voice the uncomfortable truth others avoid.',
   E'Nobody in {industry} wants to say this out loud:\n\n{the truth}.\n\nHere is why it matters: {stakes}.', true, NULL),
  ('Before and after numbers', 'Data', 'Show a concrete change with two numbers and the how.',
   E'{metric} before: {number}.\n{metric} after: {number}.\n\nWhat changed: {the lever}.\n\nThe part people miss: {insight}.', true, NULL),
  ('The benchmark', 'Data', 'Give the reader a number to measure themselves against.',
   E'If you are {audience}, here is the number that matters: {benchmark}.\n\nBelow it: {meaning}.\nAbove it: {meaning}.\n\nHow to move it: {action}.', true, NULL),
  ('The hard lesson', 'Lessons', 'A lesson that cost something to learn.',
   E'The hardest lesson {experience} taught me:\n\n{the lesson}.\n\nIt cost me {what it cost}.\n\nSo you do not pay the same price: {takeaway}.', true, NULL),
  ('The question I keep getting', 'Question', 'Answer a recurring question in public.',
   E'The question I get most about {topic}:\n\n{the question}\n\nHere is my honest answer: {answer}.\n\nWhat would you add?', true, NULL),
  ('Genuine question', 'Question', 'Ask the audience a real question to spark discussion.',
   E'Genuine question for {audience}:\n\n{the question}\n\nI have been going back and forth on {the tension}.\n\nCurious how you see it.', true, NULL),
  ('Would you rather', 'Question', 'A this-or-that prompt that reveals values.',
   E'Would you rather {option A} or {option B}?\n\nFor {topic}, I lean {your pick} because {reason}.\n\nYou?', true, NULL),
  ('Where this is going', 'Prediction', 'A grounded prediction about a trend.',
   E'Here is where {topic} is heading:\n\n{the prediction}.\n\nThe signal I am watching: {evidence}.\n\nWhat to do about it now: {action}.', true, NULL),
  ('In five years', 'Prediction', 'A longer-horizon take on how something changes.',
   E'In five years, {thing} will look nothing like today.\n\n{what changes}.\n\nThe people who prepare now by {action} will {payoff}.', true, NULL),
  ('This versus that', 'Comparison', 'A side-by-side that reveals a non-obvious insight.',
   E'{option A} vs {option B}.\n\n{option A}: {trait}.\n{option B}: {trait}.\n\nMost people pick {common pick}. I pick {your pick} because {reason}.', true, NULL),
  ('Then versus now', 'Comparison', 'Contrast an old way with a new way.',
   E'The old way to {goal}: {old approach}.\n\nThe new way: {new approach}.\n\nWhat actually changed: {the shift}.', true, NULL),
  ('Signs you are', 'Listicle', 'A relatable checklist the reader sees themselves in.',
   E'{number} signs you are {state or type}:\n\n1. {sign}\n2. {sign}\n3. {sign}\n\nIf you nodded at {number of them}, {message}.', true, NULL),
  ('Things that changed my mind', 'Listicle', 'A list of ideas that shifted your thinking.',
   E'{number} things that changed how I think about {topic}:\n\n- {idea}\n- {idea}\n- {idea}\n\nThe one I resisted longest: {the hard one}.', true, NULL),
  ('The unglamorous truth', 'Behind the scenes', 'Show the reality behind a polished outcome.',
   E'What {role or journey} actually looks like (not the highlight reel):\n\n{unglamorous reality}\n{unglamorous reality}\n{unglamorous reality}\n\nBut here is why it is worth it: {why}.', true, NULL),
  ('What you do not see', 'Behind the scenes', 'Reveal the hidden effort behind a visible result.',
   E'You see {the public result}.\n\nWhat you do not see: {hidden work}.\n\n{what you want people to understand}.', true, NULL),
  ('How they did it', 'Case study', 'Break down how someone achieved a result.',
   E'{person or company} went from {start} to {result}.\n\nHere is what they did differently:\n\n1. {move}\n2. {move}\n3. {move}\n\nWhat you can borrow: {takeaway}.', true, NULL),
  ('The teardown', 'Case study', 'Analyze why something worked, step by step.',
   E'Why {thing} worked, broken down:\n\n- {element} -> {effect}\n- {element} -> {effect}\n- {element} -> {effect}\n\nThe piece everyone copies wrong: {the nuance}.', true, NULL),
  ('The shoutout', 'Celebration', 'Publicly credit someone and say why.',
   E'Quick shoutout to {person}.\n\n{what they did}.\n\nIt mattered because {impact}.\n\nGo follow their work.', true, NULL),
  ('We did it', 'Celebration', 'Share a team or community win generously.',
   E'We did it: {the achievement}.\n\nThis was not one person. It was {who}.\n\nWhat it unlocks next: {what is next}.', true, NULL),
  ('The myth', 'Myth', 'Bust a common myth and replace it with the truth.',
   E'Myth: {the myth}.\n\nReality: {the truth}.\n\nWhy the myth persists: {reason}.\n\nWhat to do with the truth: {action}.', true, NULL),
  ('Debunked', 'Myth', 'Take apart a piece of common advice that does not hold up.',
   E'{common advice} is everywhere.\n\nIt is also wrong for most people.\n\nHere is why: {reasoning}.\n\nDo this instead: {better advice}.', true, NULL);
