-- eccoai's own template library. Original skeletons across the common
-- LinkedIn post families. Replaces earlier global seeds.
DELETE FROM post_structures WHERE user_id IS NULL;

INSERT INTO post_structures (name, hook_type, description, skeleton, approved, user_id) VALUES
  ('Best advice I ever got', 'Best advice',
   'Open with a line of advice, the moment it landed, and what it means to you now.',
   E'The best advice I ever got: {the advice}.\n\nAt the time, I {initial reaction}.\n\nYears later, here is what it really meant: {deeper meaning}.\n\n{how you use it now}', true, NULL),
  ('One thing I would tell you', 'Best advice',
   'Speak directly to a specific reader and hand them one hard-won truth.',
   E'If you are {audience or situation}, hear this:\n\n{core message}.\n\nNobody tells you {the hard truth}.\n\nSo here is the move: {practical takeaway}.', true, NULL),
  ('What I wish I knew', 'Best advice',
   'A short list of lessons framed as what you wish you had known earlier.',
   E'{number} things I wish I knew before {milestone}:\n\n1. {lesson}\n2. {lesson}\n3. {lesson}\n\nThe one that changed everything: {the key lesson}.', true, NULL),
  ('Exactly how I do it', 'Method',
   'A tactical, step-by-step walkthrough of a real process the reader can copy.',
   E'Here is exactly how I {outcome}, step by step:\n\n1. {step}\n2. {step}\n3. {step}\n4. {step}\n\nThe step everyone skips: {the overlooked step}.', true, NULL),
  ('The framework', 'Method',
   'Name a simple framework, break down its parts, then ground it in an example.',
   E'I use a simple framework for {problem}. I call it {name}.\n\n{part 1} = {meaning}\n{part 2} = {meaning}\n{part 3} = {meaning}\n\nTry it on {concrete example}.', true, NULL),
  ('Zero to one', 'Method',
   'Map the journey from a starting point to an outcome in clear phases.',
   E'How to go from {starting point} to {end point}:\n\nPhase 1: {what to do}\nPhase 2: {what to do}\nPhase 3: {what to do}\n\nStart today with {first action}.', true, NULL),
  ('The tip that took me years', 'Tip',
   'One sharp, specific tip plus the reason it works.',
   E'A {topic} tip that took me {time} to learn:\n\n{the tip}.\n\nWhy it works: {reason}.\n\nSteal it.', true, NULL),
  ('Do this, not that', 'Tip',
   'A crisp swap: the common approach versus the better one.',
   E'Stop {common approach}.\n\nStart {better approach}.\n\nThe difference: {what changes}.', true, NULL),
  ('The two-minute fix', 'Tip',
   'A tiny action that solves a common struggle, with the why.',
   E'If you {common struggle}, do this for two minutes: {the action}.\n\nIt fixes {the problem} because {reason}.', true, NULL),
  ('My actual toolkit', 'Tools',
   'A save-worthy list of the tools you genuinely use for a job.',
   E'The {number} tools I actually use for {job}:\n\n1. {tool} - {what for}\n2. {tool} - {what for}\n3. {tool} - {what for}\n\nSave this. What would you add?', true, NULL),
  ('The one resource', 'Tools',
   'If the reader uses only one thing, make it this, and show how.',
   E'If you only use one thing for {goal}, make it this: {the resource}.\n\nHere is how I use it: {how}.', true, NULL),
  ('The mistake that cost me', 'Mistakes',
   'Name a costly mistake, what you did wrong, and the right move.',
   E'The {topic} mistake that cost me {what it cost}:\n\nI {what you did wrong}.\n\nWhat I should have done: {the right move}.\n\nDo not repeat it.', true, NULL),
  ('Red flags I ignored', 'Mistakes',
   'A short list of warning signs you missed, and what to do about them.',
   E'{number} red flags I ignored in {situation}:\n\n- {red flag}\n- {red flag}\n- {red flag}\n\nIf you see these: {what to do}.', true, NULL),
  ('Stop doing this', 'Mistakes',
   'Call out a common mistake, why it backfires, and the alternative.',
   E'Stop {common mistake}. I see it constantly.\n\nHere is why it backfires: {consequence}.\n\nDo this instead: {alternative}.', true, NULL),
  ('The number', 'Milestone',
   'Lead with a milestone number, its meaning, gratitude, and what is next.',
   E'{specific number}.\n\nThat is {what it represents}.\n\nWhat it really means: {deeper meaning}.\n\nThank you to {people who helped}.\n\nNext: {forward goal}.', true, NULL),
  ('What this year taught me', 'Milestone',
   'Reflect on a period of time through a few honest lessons.',
   E'{time period} ago, I {started something}.\n\nHere is what it taught me:\n\n- {lesson}\n- {lesson}\n- {lesson}\n\nHere is to {what is next}.', true, NULL),
  ('The turning point', 'My story',
   'A vulnerable before and after: a low moment, the choice, the change.',
   E'{time ago}, I {low moment}.\n\nEveryone said {common advice}.\n\nInstead, I {the choice}.\n\nHere is what changed:\n\n- {shift}\n- {shift}\n\n{one-line takeaway}', true, NULL),
  ('Why I really started', 'My story',
   'The honest reason behind what you do, and what it means for the work.',
   E'People ask why I {what you do}.\n\nThe real reason: {the story or moment}.\n\n{what it means for the work now}.', true, NULL),
  ('I almost quit', 'My story',
   'A raw moment of nearly giving up, and what kept you going.',
   E'I almost quit {thing} {time ago}.\n\n{what was happening}.\n\nWhat kept me going: {the reason}.\n\nIf you are there right now: {message to the reader}.', true, NULL),
  ('Unpopular opinion', 'Contrarian',
   'State a contrarian take, name the consensus, then defend your view.',
   E'Unpopular opinion: {the take}.\n\nEveryone says {conventional wisdom}. I disagree.\n\nHere is why: {reasoning}.\n\n{what to do with this}.', true, NULL),
  ('The biggest lie', 'Contrarian',
   'Name a widely repeated falsehood in your space, then the truth.',
   E'The biggest lie in {industry or topic}: {the lie}.\n\nThe truth: {reality}.\n\nWhat changes when you accept it: {implication}.', true, NULL),
  ('The stat that stops you', 'Data',
   'Lead with a surprising number, make it human, and raise the real question.',
   E'{surprising statistic}.\n\nLet that sink in.\n\nBehind that number: {what it means for real people}.\n\n{the question this should force us to ask}', true, NULL),
  ('If I started over', 'Lessons',
   'What you would change, and the one thing you would keep exactly.',
   E'If I started {thing} over today, here is what I would do differently:\n\n- {change}\n- {change}\n- {change}\n\nWhat I would keep exactly the same: {the one thing}.', true, NULL);
